### ISSUE TITLE
merge with clojure links

### ISSUE THREAD

**Issue by shaunlebron** [cljsinfo/api-docs#18]
merge with clojure links (clojuredocs, grimoire, crossclj) (will address https://github.com/cljsinfo/api-docs-generator/issues/10)

code to be moved from api-docs-reporter here:
https://github.com/cljsinfo/api-docs-report/blob/70bb4ee3840f6b66fac259244a3d06eb547c3b07/src/gen/gen/core.clj#L100-L167

**Comment by shaunlebron** [comment]
we can generate clojuredocs/grimoire/crossclj links if we use the upcoming "clojure" flag to confirm that it's a valid clojure symbol

**Comment by arrdem** [comment]
:+1:

**Comment by shaunlebron** [comment]
moved to https://github.com/cljsinfo/cljs-api-docs/issues/114
